### PR TITLE
feat: `w3up open <cid>` open cid on w3s.link in browser

### PR DESCRIPTION
**Pull request by olizilla**
I find myself having to add the https://w3s.link/ipfs prefix a lot. I want a command to do it for me.

```bash
# view <cid> in default browser
w3up open bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle

# works with paths too
w3up open bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle/olizilla.png
```

a port of https://github.com/web3-storage/web3.storage/pull/1892

License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>

### CODE REVIEW

**Comment by olizilla** [comment]
In general I like having some command available in the CLI that surfaces the gateway as it feels like part of the magic to also be able to see your content there.

**Comment by jchris** [comment]
thanks for doing this!

**Comment by JeffLowe** [comment]
We'll be getting this reviewed and pulled in soon.

**Comment by the-simian** [comment]
Wanted to let you know we haven't forgotten about this, just wanted to beeline to get the CI stuff done asap. I'll catch this branch up to main and pull it in the morning. Thank you this is a cool feature

**Review by the-simian — APPROVED** [review]
I added a small amount of validation and updated this branch with main. (We were super focused on getting the CI stuff in asap)

**Pull request merged**
